language: node_js
node_js:
  - '12'
  - 'node'
script: npm run test
#after_script: "./node_modules/nyc/bin/nyc.js report --reporter=lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
notifications:
  email:
    recipients:
      - KSDaemon@ya.ru
    on_success: change
    on_failure: always

